### ISSUE TITLE
root  sshkey ?

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-users#42]
group_vars/all.yml
``` yml
users_root:
  - name:   'root'
    state:  'present'
    group:  'root'
    password: "{{ lookup('file', secret + '/users/root/password') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/root/sshkeys') }}"
      - "{{ lookup('file', secret + '/users/root/sshkeys2') }}"

users_admins:
  - users_root
```
https://github.com/debops/ansible-users/blob/master/tasks/sshkeys.yml#L14

How to be here?
I can create a patch if necessary
