### ISSUE TITLE
If primary group user is not unique (eg. "users"), removing a user fails

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-users#48]
If you'd previously added several users with a general primary group, such as 'users' (instead of group with same name as user), you get an error when you try to remove one of the users by setting the state: absent

```
users_myuser1:
  name: myuser1
  state: present
  group: users
  groups: [ sudo ]
  gid: 100
  uid: 1001
  shell: "/bin/bash"
  comment: "User 1"
  system: False
users_myuser2:
  name: myuser2
  state: absent
  group: users
  groups: [ sudo ]
  gid: 100
  uid: 1002
  shell: "/bin/bash"
  comment: "User 2"
  system: False
```
Error: 
```
groupdel: cannot remove the primary group of user 'myuser1'\n"
```

Cause seems to be in users.yml:123:
```
- name: Remove user groups if requested
  group:
    name: '{{ item.group | default(item.name) }}'
    state: 'absent'
  with_flattened:
    - '{{ users_default }}'
    - '{{ users_admins }}'
    - '{{ users_groups }}'
    - '{{ users_list }}'
    - '{{ users_group_list }}'
    - '{{ users_host_list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is defined and item.state == 'absent'))
```
It tries to delete the group even if other users are still using this group as primary group.
